version: '3.7'

services:
  arbiter:
    image: docker.iscinternal.com/intersystems/arbiter:2020.3.0-latest
    init: true
    command: 
      - /usr/local/etc/irissys/startISCAgent.sh 2188
    hostname: arbiter

  mirrorA:
    build: .
    image: demoapp
    init: true
    hostname: mirrorA
    environment: 
      - IRIS_MIRROR_ROLE=main
      - IRIS_MIRROR_ARBITER=arbiter
    ports:
      - 9092:52773
    volumes: 
      - ./:/ISC/utiles
      - ./backup:/opt/backup
      - ./init_mirror.sh:/init_mirror.sh
    command:
      --key /ISC/utiles/iris.key
      -a /init_mirror.sh

  mirrorB:
    image: demoapp
    init: true
    hostname: mirrorB
    ports:
      - 9093:52773
    environment: 
      - IRIS_MIRROR_ROLE=backup
      - IRIS_MIRROR_AGENT=mirrorA
    volumes: 
      - ./:/ISC/utiles
      - ./backup:/opt/backup
      - ./init_mirror.sh:/init_mirror.sh
    command:
      --key /ISC/utiles/iris.key
      -a /init_mirror.sh

  loadbalance:
    build: ./webgateway
    depends_on:
      - mirrorA
      - mirrorB
      - arbiter
    image: loadbalance
    ports:
    - "443:443"
    - 80:80
    environment:
      - ISC_DATA_DIRECTORY=/durable/webgateway
      - IRIS_USER=CSPsystem
      - IRIS_PASSWORD=SYS
    volumes:
      - "./webgateway:/durable"

networks:
  app_net:
    ipam:
      driver: default

volumes:
  backup:
    